/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as CvIdRouteImport } from './routes/cv.$id'
import { Route as CvNovoRouteImport } from './routes/cv.novo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CvIdIndexRouteImport } from './routes/cv.$id.index'
import { Route as CvIdEditarRouteImport } from './routes/cv.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIdRoute = CvIdRouteImport.update({
  id: '/cv/$id',
  path: '/cv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CvNovoRoute = CvNovoRouteImport.update({
  id: '/cv/novo',
  path: '/cv/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIdIndexRoute = CvIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CvIdRoute,
} as any)
const CvIdEditarRoute = CvIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => CvIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/recuperar': typeof RecuperarRoute
  '/suporte': typeof SuporteRoute
  '/cv/$id': typeof CvIdRouteWithChildren
  '/cv/novo': typeof CvNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cv/$id/editar': typeof CvIdEditarRoute
  '/cv/$id/': typeof CvIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/recuperar': typeof RecuperarRoute
  '/suporte': typeof SuporteRoute
  '/cv/novo': typeof CvNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cv/$id/editar': typeof CvIdEditarRoute
  '/cv/$id': typeof CvIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/recuperar': typeof RecuperarRoute
  '/suporte': typeof SuporteRoute
  '/cv/$id': typeof CvIdRouteWithChildren
  '/cv/novo': typeof CvNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cv/$id/editar': typeof CvIdEditarRoute
  '/cv/$id/': typeof CvIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conta'
    | '/criar-conta'
    | '/dashboard'
    | '/login'
    | '/modelos'
    | '/recuperar'
    | '/suporte'
    | '/cv/$id'
    | '/cv/novo'
    | '/api/auth/$'
    | '/cv/$id/editar'
    | '/cv/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/conta'
    | '/criar-conta'
    | '/dashboard'
    | '/login'
    | '/modelos'
    | '/recuperar'
    | '/suporte'
    | '/cv/novo'
    | '/api/auth/$'
    | '/cv/$id/editar'
    | '/cv/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conta'
    | '/criar-conta'
    | '/dashboard'
    | '/login'
    | '/modelos'
    | '/recuperar'
    | '/suporte'
    | '/cv/$id'
    | '/cv/novo'
    | '/api/auth/$'
    | '/cv/$id/editar'
    | '/cv/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContaRoute: typeof ContaRoute
  CriarContaRoute: typeof CriarContaRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ModelosRoute: typeof ModelosRoute
  RecuperarRoute: typeof RecuperarRoute
  SuporteRoute: typeof SuporteRoute
  CvIdRoute: typeof CvIdRouteWithChildren
  CvNovoRoute: typeof CvNovoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$id': {
      id: '/cv/$id'
      path: '/cv/$id'
      fullPath: '/cv/$id'
      preLoaderRoute: typeof CvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/novo': {
      id: '/cv/novo'
      path: '/cv/novo'
      fullPath: '/cv/novo'
      preLoaderRoute: typeof CvNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$id/': {
      id: '/cv/$id/'
      path: '/'
      fullPath: '/cv/$id/'
      preLoaderRoute: typeof CvIdIndexRouteImport
      parentRoute: typeof CvIdRoute
    }
    '/cv/$id/editar': {
      id: '/cv/$id/editar'
      path: '/editar'
      fullPath: '/cv/$id/editar'
      preLoaderRoute: typeof CvIdEditarRouteImport
      parentRoute: typeof CvIdRoute
    }
  }
}

interface CvIdRouteChildren {
  CvIdEditarRoute: typeof CvIdEditarRoute
  CvIdIndexRoute: typeof CvIdIndexRoute
}

const CvIdRouteChildren: CvIdRouteChildren = {
  CvIdEditarRoute: CvIdEditarRoute,
  CvIdIndexRoute: CvIdIndexRoute,
}

const CvIdRouteWithChildren = CvIdRoute._addFileChildren(CvIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContaRoute: ContaRoute,
  CriarContaRoute: CriarContaRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ModelosRoute: ModelosRoute,
  RecuperarRoute: RecuperarRoute,
  SuporteRoute: SuporteRoute,
  CvIdRoute: CvIdRouteWithChildren,
  CvNovoRoute: CvNovoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
